### PR TITLE
LoaiMasri   loaimasri2002@gmail.com

### PR DESCRIPTION
**Pull request by LoaiMasri1**
loaimasri2002@gmail.com

### CODE REVIEW

**Review by yousefalaqra — COMMENTED** [review]
Amazing Loai! 

You are for the 12 points! 

You need to work on the SQL solution to make it read from actual database!

**Comment by LoaiMasri1** [comment]
i will solve it

**Comment by yousefalaqra** [comment]
@LoaiMasri1  That's pretty good, please merge your pull-request

**Comment by LoaiMasri1** [comment]
> @LoaiMasri1 That's pretty good, please merge your pull-request

I don't have permission

**Comment by yousefalaqra** [comment]
@LoaiMasri1 

You have it now, please check

**Comment by yousefalaqra** [comment]
@LoaiMasri1 

After you complete the merge, please create one  more pr to update the README file to include a description of your solutions

**Pull request merged**
